@HostAddress = http://localhost:5159

GET {{HostAddress}}/responses/42/with-typed-results
Accept: application/json

### Get should return 404

GET {{HostAddress}}/responses/999/with-typed-results
Accept: application/json

### PATCH should return 405

PATCH {{HostAddress}}/responses/42/with-typed-results
Accept: application/json


### PUT returns 400

PUT {{HostAddress}}/responses/42/with-typed-results