@HostAddress = http://localhost:5159

# Test missing required form field

POST {{HostAddress}}/form-bodies/from-form
Content-Type: multipart/form-data; boundary=WebKitFormBoundary7MA4YWxkTrZu0gW

--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"
Content-Type: text/plain

Alfred E. Neuman
--WebKitFormBoundary7MA4YWxkTrZu0gW--
