@HostAddress = http://localhost:5044

GET {{HostAddress}}/shapes?type=triangle
Accept: application/json

###

POST {{HostAddress}}/shape-type
Accept: application/json
Content-Type: application/json

{
  "shapeType": "triangle",
  "hypotenuse": 1,
  "color": "blue",
  "sides": 3
}

###